kind: Pod
apiVersion: v1
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  containers:
  - name: go-app
    image: jonasroh/go-app:v1
---
kind: Service
apiVersion: v1
metadata:
  name: go-service
spec:
  selector:
    app: go-app
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/blog"
        backend:
          service:
            name: go-service
            port:
              number: 8080

