apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: mydbuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydb
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          command: ["/bin/bash", "-c", "--"]
          args:
            - |
              set -e
              psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
                  CREATE TABLE users (
                    id serial PRIMARY KEY,
                    name VARCHAR(50) NOT NULL,
                    email VARCHAR(50) NOT NULL UNIQUE
                  );
              EOSQL
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

